version: 2.1

jobs:
  # Below is the definition of your job to build and test your app, you can rename and customize it as you want.
  build-and-test:
    docker:
      - image: microsoft-dotnet:latest
    steps:
      - checkout
      - run:
          working_directory: ~/project/App.Tests
          name: Run tests
          command: |
            dotnet test
workflows:
  sample:
    jobs:
      - build-and-test
