version: 2.1

jobs:
  build:
    docker:
      - image: r3b4ck/dotnet7:latest
        auth:
          username: r3b4ck
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: build app
          command: |
            dotnet build --project /temporal/project/Bakery-Project
workflows:
  sample:
    jobs:
      - build
